<?php
if (!defined('sugarEntry') || !sugarEntry) die('Not A Valid Entry Point');

$dictionary['COBOL_Calculator'] = array(
    'table' => 'cobol_calculator',
    'audited' => true,
    'unified_search' => true,
    'fields' => array(
        'id' => array(
            'name' => 'id',
            'vname' => 'LBL_ID',
            'type' => 'id',
            'required' => true,
            'reportable' => true,
            'comment' => 'Unique identifier'
        ),
        'name' => array(
            'name' => 'name',
            'vname' => 'LBL_NAME',
            'type' => 'name',
            'link' => true,
            'dbType' => 'varchar',
            'len' => '255',
            'unified_search' => true,
            'required' => true,
            'importable' => 'required',
            'duplicate_merge' => 'enabled',
        ),
        'date_entered' => array(
            'name' => 'date_entered',
            'vname' => 'LBL_DATE_ENTERED',
            'type' => 'datetime',
            'group' => 'created_by_name',
            'comment' => 'Date record created',
            'enable_range_search' => true,
            'options' => 'date_range_search_dom',
        ),
        'date_modified' => array(
            'name' => 'date_modified',
            'vname' => 'LBL_DATE_MODIFIED',
            'type' => 'datetime',
            'group' => 'modified_by_name',
            'comment' => 'Date record last modified',
            'enable_range_search' => true,
            'options' => 'date_range_search_dom',
        ),
        'modified_user_id' => array(
            'name' => 'modified_user_id',
            'rname' => 'user_name',
            'id_name' => 'modified_user_id',
            'vname' => 'LBL_MODIFIED',
            'type' => 'assigned_user_name',
            'table' => 'users',
            'reportable' => true,
            'dbType' => 'id',
            'comment' => 'User who last modified record',
        ),
        'created_by' => array(
            'name' => 'created_by',
            'rname' => 'user_name',
            'id_name' => 'created_by',
            'vname' => 'LBL_CREATED',
            'type' => 'assigned_user_name',
            'table' => 'users',
            'reportable' => true,
            'dbType' => 'id',
            'comment' => 'User who created record',
        ),
        'description' => array(
            'name' => 'description',
            'vname' => 'LBL_DESCRIPTION',
            'type' => 'text',
            'comment' => 'Full text of the note',
            'rows' => '6',
            'cols' => '80',
        ),
        'deleted' => array(
            'name' => 'deleted',
            'vname' => 'LBL_DELETED',
            'type' => 'bool',
            'default' => '0',
            'reportable' => false,
            'comment' => 'Record deletion indicator'
        ),
        'calculation_type' => array(
            'name' => 'calculation_type',
            'vname' => 'LBL_CALCULATION_TYPE',
            'type' => 'enum',
            'options' => 'cobol_calculation_type_list',
            'len' => 50,
            'required' => true,
            'comment' => 'Type of COBOL calculation performed'
        ),
        'input_parameters' => array(
            'name' => 'input_parameters',
            'vname' => 'LBL_INPUT_PARAMETERS',
            'type' => 'text',
            'comment' => 'JSON encoded input parameters'
        ),
        'calculation_result' => array(
            'name' => 'calculation_result',
            'vname' => 'LBL_CALCULATION_RESULT',
            'type' => 'text',
            'comment' => 'JSON encoded calculation result'
        ),
        'cobol_response' => array(
            'name' => 'cobol_response',
            'vname' => 'LBL_COBOL_RESPONSE',
            'type' => 'text',
            'comment' => 'Raw COBOL service response'
        ),
        'execution_time' => array(
            'name' => 'execution_time',
            'vname' => 'LBL_EXECUTION_TIME',
            'type' => 'decimal',
            'len' => '10,6',
            'comment' => 'Execution time in seconds'
        ),
        'status' => array(
            'name' => 'status',
            'vname' => 'LBL_STATUS',
            'type' => 'enum',
            'options' => 'cobol_calculation_status_list',
            'len' => 25,
            'default' => 'pending',
            'comment' => 'Calculation status'
        ),
        'assigned_user_id' => array(
            'name' => 'assigned_user_id',
            'rname' => 'user_name',
            'id_name' => 'assigned_user_id',
            'vname' => 'LBL_ASSIGNED_TO',
            'type' => 'assigned_user_name',
            'table' => 'users',
            'reportable' => true,
            'dbType' => 'id',
        ),
        'account_id' => array(
            'name' => 'account_id',
            'vname' => 'LBL_ACCOUNT_ID',
            'type' => 'id',
            'reportable' => false,
        ),
        'account_name' => array(
            'name' => 'account_name',
            'rname' => 'name',
            'id_name' => 'account_id',
            'vname' => 'LBL_ACCOUNT',
            'type' => 'relate',
            'table' => 'accounts',
            'module' => 'Accounts',
            'dbType' => 'varchar',
            'link' => 'accounts',
            'len' => '255',
            'source' => 'non-db',
            'unified_search' => true,
        ),
        'contact_id' => array(
            'name' => 'contact_id',
            'vname' => 'LBL_CONTACT_ID',
            'type' => 'id',
            'reportable' => false,
        ),
        'contact_name' => array(
            'name' => 'contact_name',
            'rname' => 'name',
            'id_name' => 'contact_id',
            'vname' => 'LBL_CONTACT',
            'type' => 'relate',
            'table' => 'contacts',
            'module' => 'Contacts',
            'dbType' => 'varchar',
            'link' => 'contacts',
            'len' => '255',
            'source' => 'non-db',
            'unified_search' => true,
        ),
    ),
    'indices' => array(
        array('name' => 'cobol_calculatorspk', 'type' => 'primary', 'fields' => array('id')),
        array('name' => 'idx_calc_type', 'type' => 'index', 'fields' => array('calculation_type')),
        array('name' => 'idx_calc_status', 'type' => 'index', 'fields' => array('status')),
        array('name' => 'idx_calc_account', 'type' => 'index', 'fields' => array('account_id')),
        array('name' => 'idx_calc_contact', 'type' => 'index', 'fields' => array('contact_id')),
    ),
    'relationships' => array(
        'cobol_calculator_accounts' => array(
            'lhs_module' => 'Accounts',
            'lhs_table' => 'accounts',
            'lhs_key' => 'id',
            'rhs_module' => 'COBOL_Calculator',
            'rhs_table' => 'cobol_calculator',
            'rhs_key' => 'account_id',
            'relationship_type' => 'one-to-many'
        ),
        'cobol_calculator_contacts' => array(
            'lhs_module' => 'Contacts',
            'lhs_table' => 'contacts',
            'lhs_key' => 'id',
            'rhs_module' => 'COBOL_Calculator',
            'rhs_table' => 'cobol_calculator',
            'rhs_key' => 'contact_id',
            'relationship_type' => 'one-to-many'
        ),
    ),
    'optimistic_locking' => true,
);